- name: Ansible Pull
  hosts: localhost
  become: true

  roles:
    - packages
    - unattended-upgrades

  tasks:
    - name: Create ansible-pull success marker
      ansible.builtin.copy:
        content: "ansible-pull last run: {{ ansible_date_time.iso8601 }}\n"
        dest: /etc/ansible-pull-last-run

- name: Web server setup
  hosts: webservers
  become: true

  vars_files:
    - vars/vault.yml

  roles:
    - caddy
