- name: Ansible Pull
  hosts: localhost
  become: true

  tasks:
    - name: Create ansible-pull success marker
      ansible.builtin.copy:
        content: "ansible-pull last run: {{ ansible_date_time.iso8601 }}\n"
        dest: /etc/ansible-pull-last-run
