- name: Create ansible user
  ansible.builtin.user:
    name: ansy
    shell: /bin/bash
    home: /home/ansy
    create_home: true
    state: present

- name: Ensure sudoers.d directory exists
  ansible.builtin.file:
    path: /etc/sudoers.d
    state: directory
    mode: '0750'

- name: Install sudo
  ansible.builtin.apt:
    name: sudo
    state: present

- name: Grant ansible user passwordless sudo
  ansible.builtin.copy:
    content: "ansy ALL=(ALL) NOPASSWD:ALL\n"
    dest: /etc/sudoers.d/ansy
    mode: '0440'
    validate: /usr/sbin/visudo -cf %s
