---
- name: Check if Docker is installed
  ansible.builtin.command: docker -v
  register: docker_installed
  ignore_errors: true

- name: Install Docker
  when: docker_installed.failed
  block:
    - name: Install dependencies
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present
        update_cache: true

    - name: Create keyrings directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Add Docker GPG key
      ansible.builtin.shell:
        cmd: |
          curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          chmod a+r /etc/apt/keyrings/docker.gpg
        creates: /etc/apt/keyrings/docker.gpg

    - name: Add Docker apt repository
      ansible.builtin.shell:
        cmd: |
          echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
          $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
          tee /etc/apt/sources.list.d/docker.list > /dev/null
        creates: /etc/apt/sources.list.d/docker.list

    - name: Install Docker packages
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: true

- name: Ensure Docker is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Ensure Docker group exists
  ansible.builtin.group:
    name: docker
    state: present

- name: Add lennon to docker group
  ansible.builtin.user:
    name: lennon
    groups: docker
    append: true
